- name: Prepare mounts
  hosts: hosts
  gather_facts: true
  become: yes
  vars_files:
    - appVars.yml
  vars:
    mountAppServerLocation: "nas.my-company.com:/mnt/hdd_pool0/app"
    mountType: "nfs"
  tasks:
    - name: Create harbor database mount directory
      file:
        path: "{{ appDataDir }}"
        state: directory

    - name: Create data-app.mount file
      template:
        src: templates/data-app.mount.j2
        dest: /etc/systemd/system/data-app.mount
        mode: '0644'

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes

    - name: Start and enable data-app.mount
      systemd:
        name: data-app.mount
        enabled: yes
        state: started
        daemon_reload: yes
